import dotenv from "dotenv"
dotenv.config({ path: ".env.local" })
dotenv.config()
import { PrismaClient } from "@/lib/generated/prisma"
import { PrismaPg } from "@prisma/adapter-pg"
import type { RustLevel } from "@/lib/generated/prisma"

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! })
const prisma = new PrismaClient({ adapter })

const companies = [
  {
    name: "Cloudflare",
    slug: "cloudflare",
    logoUrl: "https://logo.clearbit.com/cloudflare.com",
    description: "Global network platform delivering security, performance, and reliability at scale. Heavy Rust usage in their networking stack.",
    careersUrl: "https://www.cloudflare.com/careers/jobs/",
    loginUrl: "https://dash.cloudflare.com/login",
    tags: ["Rust", "Infrastructure", "Networking", "Security", "Cloud"],
    remote: true,
    rustLevel: "HEAVY" as RustLevel,
    atsProvider: "Greenhouse",
  },
  {
    name: "Fly.io",
    slug: "fly-io",
    logoUrl: "https://logo.clearbit.com/fly.io",
    description: "Deploy apps close to your users on a global platform. Rust-first infrastructure team building the next generation of cloud.",
    careersUrl: "https://fly.io/jobs/",
    loginUrl: "https://fly.io/dashboard",
    tags: ["Rust", "Cloud", "DevTools", "Infrastructure", "Networking"],
    remote: true,
    rustLevel: "HEAVY" as RustLevel,
    atsProvider: null,
  },
  {
    name: "Oxide Computer",
    slug: "oxide-computer",
    logoUrl: "https://logo.clearbit.com/oxide.computer",
    description: "Building the first commercial cloud computer. Everything is Rust — firmware, OS, hypervisor, control plane.",
    careersUrl: "https://oxide.computer/careers",
    loginUrl: null,
    tags: ["Rust", "Systems", "Linux", "Hardware", "Performance"],
    remote: false,
    rustLevel: "CORE" as RustLevel,
    atsProvider: null,
  },
  {
    name: "Turso",
    slug: "turso",
    logoUrl: "https://logo.clearbit.com/turso.tech",
    description: "Edge-hosted SQLite databases built on libSQL. Core infrastructure written in Rust with a focus on developer experience.",
    careersUrl: "https://turso.tech/careers",
    loginUrl: "https://app.turso.tech",
    tags: ["Rust", "Databases", "Open Source", "Performance"],
    remote: true,
    rustLevel: "CORE" as RustLevel,
    atsProvider: null,
  },
  {
    name: "Zed Industries",
    slug: "zed-industries",
    logoUrl: "https://logo.clearbit.com/zed.dev",
    description: "Building the next-generation code editor in Rust. GPU-accelerated, collaborative, and blazing fast.",
    careersUrl: "https://zed.dev/jobs",
    loginUrl: null,
    tags: ["Rust", "DevTools", "Performance", "Open Source", "Compilers"],
    remote: true,
    rustLevel: "CORE" as RustLevel,
    atsProvider: null,
  },
  {
    name: "Canonical",
    slug: "canonical",
    logoUrl: "https://logo.clearbit.com/canonical.com",
    description: "The company behind Ubuntu Linux. Building open source infrastructure software for cloud, IoT, and enterprise.",
    careersUrl: "https://canonical.com/careers",
    loginUrl: null,
    tags: ["Linux", "Infrastructure", "Open Source", "Cloud", "Systems"],
    remote: true,
    rustLevel: "NONE" as RustLevel,
    atsProvider: null,
  },
  {
    name: "Datadog",
    slug: "datadog",
    logoUrl: "https://logo.clearbit.com/datadoghq.com",
    description: "Cloud monitoring and observability platform. Engineering Rust into their high-performance data pipelines.",
    careersUrl: "https://www.datadoghq.com/careers/",
    loginUrl: "https://app.datadoghq.com",
    tags: ["Observability", "Infrastructure", "Backend", "Cloud", "Rust"],
    remote: true,
    rustLevel: "PARTIAL" as RustLevel,
    atsProvider: "Greenhouse",
  },
  {
    name: "Grafana Labs",
    slug: "grafana-labs",
    logoUrl: "https://logo.clearbit.com/grafana.com",
    description: "The open and composable observability and data visualization platform. Grafana, Loki, Tempo, and more.",
    careersUrl: "https://grafana.com/about/careers/",
    loginUrl: "https://grafana.com/auth/sign-in/",
    tags: ["Observability", "Open Source", "Backend", "Infrastructure"],
    remote: true,
    rustLevel: "NONE" as RustLevel,
    atsProvider: "Greenhouse",
  },
  {
    name: "Discord",
    slug: "discord",
    logoUrl: "https://logo.clearbit.com/discord.com",
    description: "Communication platform for communities. Rewrote critical services in Rust for performance at scale.",
    careersUrl: "https://discord.com/careers",
    loginUrl: "https://discord.com/login",
    tags: ["Rust", "Backend", "Distributed Systems", "Performance"],
    remote: true,
    rustLevel: "PARTIAL" as RustLevel,
    atsProvider: "Greenhouse",
  },
  {
    name: "Fastly",
    slug: "fastly",
    logoUrl: "https://logo.clearbit.com/fastly.com",
    description: "Edge cloud platform powering the world's fastest websites. Rust is used in Compute@Edge and their Varnish replacement.",
    careersUrl: "https://www.fastly.com/about/careers/",
    loginUrl: "https://manage.fastly.com",
    tags: ["Rust", "Networking", "Infrastructure", "Cloud", "Performance"],
    remote: true,
    rustLevel: "HEAVY" as RustLevel,
    atsProvider: "Lever",
  },
  {
    name: "GitLab",
    slug: "gitlab",
    logoUrl: "https://logo.clearbit.com/gitlab.com",
    description: "The complete DevOps platform delivered as a single application. Fully remote company with 2,000+ employees.",
    careersUrl: "https://about.gitlab.com/jobs/",
    loginUrl: "https://gitlab.com/users/sign_in",
    tags: ["Backend", "DevTools", "Open Source", "Infrastructure"],
    remote: true,
    rustLevel: "NONE" as RustLevel,
    atsProvider: "Greenhouse",
  },
  {
    name: "Elastic",
    slug: "elastic",
    logoUrl: "https://logo.clearbit.com/elastic.co",
    description: "Search, observability, and security at scale. Elasticsearch, Kibana, Beats, and Logstash.",
    careersUrl: "https://www.elastic.co/careers/",
    loginUrl: "https://cloud.elastic.co",
    tags: ["Backend", "Distributed Systems", "Databases", "Observability"],
    remote: true,
    rustLevel: "NONE" as RustLevel,
    atsProvider: "Greenhouse",
  },
  {
    name: "Sentry",
    slug: "sentry",
    logoUrl: "https://logo.clearbit.com/sentry.io",
    description: "Application monitoring with full stack error tracking. Relay (ingestion layer) is written in Rust.",
    careersUrl: "https://sentry.io/careers/",
    loginUrl: "https://sentry.io/auth/login/",
    tags: ["Rust", "Observability", "Open Source", "Backend"],
    remote: true,
    rustLevel: "PARTIAL" as RustLevel,
    atsProvider: "Lever",
  },
  {
    name: "Mozilla",
    slug: "mozilla",
    logoUrl: "https://logo.clearbit.com/mozilla.org",
    description: "The organization behind Firefox and the creators of Rust. Deep expertise in systems programming and browser engineering.",
    careersUrl: "https://www.mozilla.org/en-US/careers/listings/",
    loginUrl: null,
    tags: ["Rust", "Systems", "Open Source", "Security", "Compilers"],
    remote: true,
    rustLevel: "CORE" as RustLevel,
    atsProvider: "Greenhouse",
  },
  {
    name: "ClickHouse",
    slug: "clickhouse",
    logoUrl: "https://logo.clearbit.com/clickhouse.com",
    description: "The fastest and most resource-efficient real-time data warehouse. Open source with a cloud offering.",
    careersUrl: "https://clickhouse.com/company/careers",
    loginUrl: "https://clickhouse.cloud/signIn",
    tags: ["Databases", "Performance", "Backend", "Open Source", "Distributed Systems"],
    remote: true,
    rustLevel: "NONE" as RustLevel,
    atsProvider: "Greenhouse",
  },
  {
    name: "Cockroach Labs",
    slug: "cockroach-labs",
    logoUrl: "https://logo.clearbit.com/cockroachlabs.com",
    description: "Distributed SQL database built for global scale. CockroachDB is the cloud-native, distributed SQL database.",
    careersUrl: "https://www.cockroachlabs.com/careers/",
    loginUrl: "https://cockroachlabs.cloud/",
    tags: ["Databases", "Distributed Systems", "Backend", "Cloud"],
    remote: true,
    rustLevel: "NONE" as RustLevel,
    atsProvider: "Lever",
  },
  {
    name: "Materialize",
    slug: "materialize",
    logoUrl: "https://logo.clearbit.com/materialize.com",
    description: "Real-time data warehouse powered by streaming SQL. Built in Rust on top of Timely Dataflow.",
    careersUrl: "https://materialize.com/careers/",
    loginUrl: "https://console.materialize.com/",
    tags: ["Rust", "Databases", "Distributed Systems", "Streaming", "Performance"],
    remote: true,
    rustLevel: "CORE" as RustLevel,
    atsProvider: null,
  },
  {
    name: "Deepgram",
    slug: "deepgram",
    logoUrl: "https://logo.clearbit.com/deepgram.com",
    description: "AI speech recognition API built on GPU-accelerated neural networks. Core systems in Rust.",
    careersUrl: "https://deepgram.com/company/careers",
    loginUrl: "https://console.deepgram.com",
    tags: ["Rust", "AI Infra", "Backend", "Performance"],
    remote: true,
    rustLevel: "HEAVY" as RustLevel,
    atsProvider: "Lever",
  },
  {
    name: "Sourcegraph",
    slug: "sourcegraph",
    logoUrl: "https://logo.clearbit.com/sourcegraph.com",
    description: "Universal code search for every developer and company. Code intelligence platform at scale.",
    careersUrl: "https://sourcegraph.com/careers",
    loginUrl: "https://sourcegraph.com/.auth/openidconnect/login",
    tags: ["DevTools", "Backend", "Open Source", "Infrastructure"],
    remote: true,
    rustLevel: "NONE" as RustLevel,
    atsProvider: "Greenhouse",
  },
  {
    name: "Warp",
    slug: "warp",
    logoUrl: "https://logo.clearbit.com/warp.dev",
    description: "The terminal for the 21st century. GPU-accelerated, built in Rust with collaborative features.",
    careersUrl: "https://www.warp.dev/careers",
    loginUrl: null,
    tags: ["Rust", "DevTools", "Performance", "Systems"],
    remote: true,
    rustLevel: "CORE" as RustLevel,
    atsProvider: null,
  },
  {
    name: "Hetzner",
    slug: "hetzner",
    logoUrl: "https://logo.clearbit.com/hetzner.com",
    description: "German cloud hosting and data center company offering affordable, high-performance dedicated servers and cloud VMs.",
    careersUrl: "https://www.hetzner.com/unternehmen/jobs/",
    loginUrl: "https://accounts.hetzner.com",
    tags: ["Infrastructure", "Cloud", "Linux", "Networking"],
    remote: false,
    rustLevel: "NONE" as RustLevel,
    atsProvider: null,
  },
  {
    name: "JetBrains",
    slug: "jetbrains",
    logoUrl: "https://logo.clearbit.com/jetbrains.com",
    description: "Makers of IntelliJ IDEA, CLion, RustRover, and 15+ developer tools. Deep investment in Rust tooling.",
    careersUrl: "https://www.jetbrains.com/careers/jobs/",
    loginUrl: "https://account.jetbrains.com",
    tags: ["DevTools", "Rust", "Compilers", "Backend"],
    remote: true,
    rustLevel: "PARTIAL" as RustLevel,
    atsProvider: "SmartRecruiters",
  },
  {
    name: "Vercel",
    slug: "vercel",
    logoUrl: "https://logo.clearbit.com/vercel.com",
    description: "Frontend cloud platform for developers. Infrastructure team uses Rust in performance-critical components.",
    careersUrl: "https://vercel.com/careers",
    loginUrl: "https://vercel.com/login",
    tags: ["Infrastructure", "DevTools", "Cloud", "Backend"],
    remote: true,
    rustLevel: "PARTIAL" as RustLevel,
    atsProvider: "Greenhouse",
  },
  {
    name: "Mux",
    slug: "mux",
    logoUrl: "https://logo.clearbit.com/mux.com",
    description: "Video infrastructure for developers. APIs for video hosting, streaming, and real-time analytics.",
    careersUrl: "https://www.mux.com/jobs",
    loginUrl: "https://dashboard.mux.com",
    tags: ["Backend", "Infrastructure", "Distributed Systems", "Performance"],
    remote: true,
    rustLevel: "NONE" as RustLevel,
    atsProvider: "Lever",
  },
  {
    name: "Timescale",
    slug: "timescale",
    logoUrl: "https://logo.clearbit.com/timescale.com",
    description: "PostgreSQL for time-series data. TimescaleDB is the leading open-source time-series SQL database.",
    careersUrl: "https://www.timescale.com/careers",
    loginUrl: "https://console.cloud.timescale.com",
    tags: ["Databases", "Open Source", "Backend", "Distributed Systems"],
    remote: true,
    rustLevel: "NONE" as RustLevel,
    atsProvider: "Lever",
  },
  {
    name: "Hugging Face",
    slug: "hugging-face",
    logoUrl: "https://logo.clearbit.com/huggingface.co",
    description: "The AI community building the future. ML model hosting, datasets, and inference infrastructure. Candle ML framework in Rust.",
    careersUrl: "https://apply.workable.com/huggingface/",
    loginUrl: "https://huggingface.co/login",
    tags: ["Rust", "AI Infra", "Open Source", "Backend", "Infrastructure"],
    remote: true,
    rustLevel: "PARTIAL" as RustLevel,
    atsProvider: "Workable",
  },
  {
    name: "Ferrous Systems",
    slug: "ferrous-systems",
    logoUrl: "https://logo.clearbit.com/ferrous-systems.com",
    description: "The leading Rust consulting and training company. Creators of Ferrocene, the qualified Rust toolchain.",
    careersUrl: "https://ferrous-systems.com/",
    loginUrl: null,
    tags: ["Rust", "Systems", "Compilers", "Open Source"],
    remote: true,
    rustLevel: "CORE" as RustLevel,
    atsProvider: null,
  },
  {
    name: "Red Hat",
    slug: "red-hat",
    logoUrl: "https://logo.clearbit.com/redhat.com",
    description: "The world's leading provider of enterprise open source solutions. Significant Rust investment in system-level projects.",
    careersUrl: "https://www.redhat.com/en/jobs",
    loginUrl: "https://sso.redhat.com",
    tags: ["Linux", "Open Source", "Systems", "Infrastructure", "Security"],
    remote: true,
    rustLevel: "PARTIAL" as RustLevel,
    atsProvider: "Workday",
  },
  {
    name: "Turing",
    slug: "turing",
    logoUrl: "https://logo.clearbit.com/turing.com",
    description: "Remote engineering jobs platform connecting developers with top US tech companies. Fully remote.",
    careersUrl: "https://www.turing.com/jobs",
    loginUrl: "https://engineers.turing.com",
    tags: ["Backend", "Infrastructure", "Remote"],
    remote: true,
    rustLevel: "NONE" as RustLevel,
    atsProvider: null,
  },
  {
    name: "Tokio",
    slug: "tokio-rs",
    logoUrl: null,
    description: "The async runtime for Rust. Tokio Company is the commercial entity behind the tokio async runtime and Tower ecosystem.",
    careersUrl: "https://tokio.rs",
    loginUrl: null,
    tags: ["Rust", "Open Source", "Backend", "Systems", "Networking"],
    remote: true,
    rustLevel: "CORE" as RustLevel,
    atsProvider: null,
  },
  {
    name: "Temporal",
    slug: "temporal",
    logoUrl: "https://logo.clearbit.com/temporal.io",
    description: "Durable execution platform for building reliable distributed applications. Open source workflow orchestration.",
    careersUrl: "https://temporal.io/careers",
    loginUrl: "https://cloud.temporal.io",
    tags: ["Distributed Systems", "Backend", "Open Source", "Infrastructure"],
    remote: true,
    rustLevel: "NONE" as RustLevel,
    atsProvider: "Greenhouse",
  },
  {
    name: "Tailscale",
    slug: "tailscale",
    logoUrl: "https://logo.clearbit.com/tailscale.com",
    description: "Zero-config VPN built on WireGuard. Making networking easy for developers and enterprises.",
    careersUrl: "https://tailscale.com/careers/",
    loginUrl: "https://login.tailscale.com",
    tags: ["Networking", "Security", "Infrastructure", "Backend"],
    remote: true,
    rustLevel: "NONE" as RustLevel,
    atsProvider: null,
  },
  {
    name: "1Password",
    slug: "1password",
    logoUrl: "https://logo.clearbit.com/1password.com",
    description: "Password manager and secrets management. Significant portions of their cross-platform client and infrastructure use Rust.",
    careersUrl: "https://1password.com/careers",
    loginUrl: "https://my.1password.com",
    tags: ["Rust", "Security", "Backend", "Systems"],
    remote: true,
    rustLevel: "HEAVY" as RustLevel,
    atsProvider: "Lever",
  },
  {
    name: "Parity Technologies",
    slug: "parity-technologies",
    logoUrl: "https://logo.clearbit.com/parity.io",
    description: "Core Ethereum and blockchain infrastructure company. Substrate (Polkadot framework) is written in Rust.",
    careersUrl: "https://www.parity.io/jobs",
    loginUrl: null,
    tags: ["Rust", "Distributed Systems", "Systems", "Open Source"],
    remote: true,
    rustLevel: "CORE" as RustLevel,
    atsProvider: null,
  },
  {
    name: "Palantir",
    slug: "palantir",
    logoUrl: "https://logo.clearbit.com/palantir.com",
    description: "Data analytics and intelligence platform for governments and enterprises. Large-scale distributed systems.",
    careersUrl: "https://jobs.lever.co/palantir",
    loginUrl: null,
    tags: ["Backend", "Distributed Systems", "Infrastructure", "Security"],
    remote: false,
    rustLevel: "NONE" as RustLevel,
    atsProvider: "Greenhouse",
  },
  {
    name: "Databricks",
    slug: "databricks",
    logoUrl: "https://logo.clearbit.com/databricks.com",
    description: "Unified analytics platform for data engineering, data science, and machine learning at scale.",
    careersUrl: "https://www.databricks.com/company/careers",
    loginUrl: "https://accounts.cloud.databricks.com",
    tags: ["Backend", "Distributed Systems", "AI Infra", "Cloud", "Databases"],
    remote: true,
    rustLevel: "NONE" as RustLevel,
    atsProvider: "Greenhouse",
  },
  {
    name: "HashiCorp",
    slug: "hashicorp",
    logoUrl: "https://logo.clearbit.com/hashicorp.com",
    description: "Infrastructure automation software (Terraform, Vault, Consul, Nomad). Now part of IBM.",
    careersUrl: "https://www.hashicorp.com/careers",
    loginUrl: "https://app.terraform.io",
    tags: ["Infrastructure", "DevTools", "Open Source", "Cloud", "Security"],
    remote: true,
    rustLevel: "NONE" as RustLevel,
    atsProvider: "Greenhouse",
  },
  {
    name: "AWS",
    slug: "aws",
    logoUrl: "https://logo.clearbit.com/aws.amazon.com",
    description: "Amazon Web Services — cloud computing. Heavy Rust adoption in Firecracker, Bottlerocket, and other services.",
    careersUrl: "https://aws.amazon.com/careers/",
    loginUrl: "https://console.aws.amazon.com",
    tags: ["Rust", "Cloud", "Infrastructure", "Distributed Systems", "Systems"],
    remote: true,
    rustLevel: "HEAVY" as RustLevel,
    atsProvider: "Amazon Jobs",
  },
  {
    name: "Ardan Labs",
    slug: "ardan-labs",
    logoUrl: "https://logo.clearbit.com/ardanlabs.com",
    description: "Elite Go and Rust training and consulting company. Known for Bill Kennedy's Ultimate Go course.",
    careersUrl: "https://www.ardanlabs.com/",
    loginUrl: null,
    tags: ["Rust", "Backend", "Systems", "Open Source"],
    remote: true,
    rustLevel: "PARTIAL" as RustLevel,
    atsProvider: null,
  },
  {
    name: "Neon",
    slug: "neon",
    logoUrl: "https://logo.clearbit.com/neon.tech",
    description: "Serverless Postgres with branching. The storage layer and compute node are built in Rust.",
    careersUrl: "https://neon.tech/careers",
    loginUrl: "https://console.neon.tech",
    tags: ["Rust", "Databases", "Cloud", "Open Source", "Performance"],
    remote: true,
    rustLevel: "CORE" as RustLevel,
    atsProvider: "Lever",
  },
  {
    name: "Tremor",
    slug: "tremor",
    logoUrl: null,
    description: "Event processing system written in Rust for wayfair-scale data pipelines. Now an open source CNCF project.",
    careersUrl: "https://www.tremor.rs",
    loginUrl: null,
    tags: ["Rust", "Distributed Systems", "Backend", "Open Source", "Observability"],
    remote: true,
    rustLevel: "CORE" as RustLevel,
    atsProvider: null,
  },
  {
    name: "Figma",
    slug: "figma",
    logoUrl: "https://logo.clearbit.com/figma.com",
    description: "Collaborative design platform. Uses Rust for WebAssembly performance-critical rendering components.",
    careersUrl: "https://www.figma.com/careers/",
    loginUrl: "https://figma.com/login",
    tags: ["Rust", "Backend", "DevTools", "Performance"],
    remote: true,
    rustLevel: "PARTIAL" as RustLevel,
    atsProvider: "Greenhouse",
  },
  {
    name: "Linear",
    slug: "linear",
    logoUrl: "https://logo.clearbit.com/linear.app",
    description: "The issue tracker that makes software development faster. Known for speed, design, and developer experience.",
    careersUrl: "https://linear.app/careers",
    loginUrl: "https://linear.app/login",
    tags: ["DevTools", "Backend", "Performance"],
    remote: true,
    rustLevel: "NONE" as RustLevel,
    atsProvider: null,
  },
  {
    name: "Notion",
    slug: "notion",
    logoUrl: "https://logo.clearbit.com/notion.so",
    description: "All-in-one workspace for notes, docs, and collaboration. Strong backend and infrastructure teams.",
    careersUrl: "https://www.notion.so/careers",
    loginUrl: "https://www.notion.so/login",
    tags: ["Backend", "Infrastructure", "Distributed Systems"],
    remote: false,
    rustLevel: "NONE" as RustLevel,
    atsProvider: "Greenhouse",
  },
  {
    name: "PlanetScale",
    slug: "planetscale",
    logoUrl: "https://logo.clearbit.com/planetscale.com",
    description: "Serverless MySQL platform powered by Vitess. Horizontally scalable database for modern applications.",
    careersUrl: "https://planetscale.com/careers",
    loginUrl: "https://app.planetscale.com",
    tags: ["Databases", "Cloud", "Backend", "Distributed Systems"],
    remote: true,
    rustLevel: "NONE" as RustLevel,
    atsProvider: "Lever",
  },
  {
    name: "Stripe",
    slug: "stripe",
    logoUrl: "https://logo.clearbit.com/stripe.com",
    description: "Financial infrastructure for the internet. Massive distributed systems powering global payments.",
    careersUrl: "https://stripe.com/jobs",
    loginUrl: "https://dashboard.stripe.com/login",
    tags: ["Backend", "Distributed Systems", "Security", "Infrastructure"],
    remote: true,
    rustLevel: "NONE" as RustLevel,
    atsProvider: "Lever",
  },
  {
    name: "Shopify",
    slug: "shopify",
    logoUrl: "https://logo.clearbit.com/shopify.com",
    description: "Commerce platform for millions of businesses worldwide. Large engineering org with strong remote culture.",
    careersUrl: "https://www.shopify.com/careers",
    loginUrl: "https://accounts.shopify.com",
    tags: ["Backend", "Infrastructure", "Distributed Systems", "Cloud"],
    remote: true,
    rustLevel: "NONE" as RustLevel,
    atsProvider: "Greenhouse",
  },
  {
    name: "Apple (SEAR)",
    slug: "apple-sear",
    logoUrl: "https://logo.clearbit.com/apple.com",
    description: "Apple's Swift and Rust ecosystem team. Working on language runtimes, compilers, and systems programming.",
    careersUrl: "https://jobs.apple.com",
    loginUrl: null,
    tags: ["Rust", "Compilers", "Systems", "Performance"],
    remote: false,
    rustLevel: "PARTIAL" as RustLevel,
    atsProvider: "iCIMS",
  },
  {
    name: "Google (Android)",
    slug: "google-android",
    logoUrl: "https://logo.clearbit.com/google.com",
    description: "The Android platform team is adopting Rust as a memory-safe system language alongside C++.",
    careersUrl: "https://careers.google.com",
    loginUrl: null,
    tags: ["Rust", "Systems", "Linux", "Security", "Performance"],
    remote: false,
    rustLevel: "PARTIAL" as RustLevel,
    atsProvider: "Google Hire",
  },
  {
    name: "Microsoft (RUST)",
    slug: "microsoft-rust",
    logoUrl: "https://logo.clearbit.com/microsoft.com",
    description: "Microsoft has adopted Rust extensively in Windows, Azure, and their security-critical systems.",
    careersUrl: "https://careers.microsoft.com",
    loginUrl: null,
    tags: ["Rust", "Systems", "Cloud", "Security", "Windows"],
    remote: true,
    rustLevel: "HEAVY" as RustLevel,
    atsProvider: "Microsoft",
  },
  {
    name: "Signal",
    slug: "signal",
    logoUrl: "https://logo.clearbit.com/signal.org",
    description: "Encrypted messaging app with a mission to build private communication tools. Uses Rust in signal-zkgroup and other cryptographic libraries.",
    careersUrl: "https://signal.org/workworkwork/",
    loginUrl: null,
    tags: ["Rust", "Security", "Backend", "Open Source", "Systems"],
    remote: true,
    rustLevel: "PARTIAL" as RustLevel,
    atsProvider: null,
  },
  {
    name: "Dropbox",
    slug: "dropbox",
    logoUrl: "https://logo.clearbit.com/dropbox.com",
    description: "Cloud storage and collaboration company. Rewrote their sync engine from Python to Rust.",
    careersUrl: "https://jobs.dropbox.com",
    loginUrl: "https://www.dropbox.com/login",
    tags: ["Rust", "Systems", "Backend", "Distributed Systems"],
    remote: true,
    rustLevel: "PARTIAL" as RustLevel,
    atsProvider: "Greenhouse",
  },
  {
    name: "Svix",
    slug: "svix",
    logoUrl: "https://logo.clearbit.com/svix.com",
    description: "Webhooks as a service. The enterprise-grade webhook service for developers. Built in Rust.",
    careersUrl: "https://www.svix.com/careers/",
    loginUrl: "https://dashboard.svix.com",
    tags: ["Rust", "Backend", "Infrastructure", "Open Source"],
    remote: true,
    rustLevel: "CORE" as RustLevel,
    atsProvider: null,
  },
  {
    name: "EmbarkStudios",
    slug: "embark-studios",
    logoUrl: "https://logo.clearbit.com/embark-studios.com",
    description: "Stockholm-based game studio pushing Rust adoption in game development. Creators of rust-gpu and other open source tools.",
    careersUrl: "https://www.embark-studios.com/jobs",
    loginUrl: null,
    tags: ["Rust", "Open Source", "Systems", "Performance"],
    remote: false,
    rustLevel: "CORE" as RustLevel,
    atsProvider: null,
  },
]

async function main() {
  console.log("Seeding database...")

  for (const company of companies) {
    await prisma.company.upsert({
      where: { slug: company.slug },
      create: company,
      update: company,
    })
    console.log(`  ✓ ${company.name}`)
  }

  const count = await prisma.company.count()
  console.log(`\nDone! ${count} companies in database.`)
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
