import dotenv from "dotenv"
dotenv.config({ path: ".env.local" })
dotenv.config()
import { PrismaClient } from "@prisma/client"
import { PrismaPg } from "@prisma/adapter-pg"
import type { RustLevel, CompanyCategory, OpportunitySource, ExperienceLevel, RustSignal } from "@prisma/client"

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! })
const prisma = new PrismaClient({ adapter })

const companies = [
  {
    name: "Cloudflare",
    slug: "cloudflare",
    logoUrl: null,
    description: "Global network platform delivering security, performance, and reliability at scale. Heavy Rust usage in their networking stack.",
    careersUrl: "https://www.cloudflare.com/careers/jobs/",
    loginUrl: "https://dash.cloudflare.com/login",
    tags: ["Rust", "Infrastructure", "Networking", "Security", "Cloud"],
    remote: true,
    rustLevel: "HEAVY" as RustLevel,
    atsProvider: "Greenhouse",
    category: "NETWORKING" as CompanyCategory,
    juniorAccessible: false,
  },
  {
    name: "Fly.io",
    slug: "fly-io",
    logoUrl: null,
    description: "Deploy apps close to your users on a global platform. Rust-first infrastructure team building the next generation of cloud.",
    careersUrl: "https://fly.io/jobs/",
    loginUrl: "https://fly.io/dashboard",
    tags: ["Rust", "Cloud", "DevTools", "Infrastructure", "Networking"],
    remote: true,
    rustLevel: "HEAVY" as RustLevel,
    atsProvider: null,
    category: "CLOUD_PLATFORM" as CompanyCategory,
    juniorAccessible: false,
  },
  {
    name: "Oxide Computer",
    slug: "oxide-computer",
    logoUrl: null,
    description: "Building the first commercial cloud computer. Everything is Rust — firmware, OS, hypervisor, control plane.",
    careersUrl: "https://oxide.computer/careers",
    loginUrl: null,
    tags: ["Rust", "Systems", "Linux", "Hardware", "Performance"],
    remote: false,
    rustLevel: "CORE" as RustLevel,
    atsProvider: null,
    category: "SYSTEMS" as CompanyCategory,
    juniorAccessible: false,
  },
  {
    name: "Turso",
    slug: "turso",
    logoUrl: null,
    description: "Edge-hosted SQLite databases built on libSQL. Core infrastructure written in Rust with a focus on developer experience.",
    careersUrl: "https://turso.tech/careers",
    loginUrl: "https://app.turso.tech",
    tags: ["Rust", "Databases", "Open Source", "Performance"],
    remote: true,
    rustLevel: "CORE" as RustLevel,
    atsProvider: null,
    category: "DATABASES" as CompanyCategory,
    juniorAccessible: true,
    openSourceRepo: "https://github.com/tursodatabase/libsql",
  },
  {
    name: "Zed Industries",
    slug: "zed-industries",
    logoUrl: null,
    description: "Building the next-generation code editor in Rust. GPU-accelerated, collaborative, and blazing fast.",
    careersUrl: "https://zed.dev/jobs",
    loginUrl: null,
    tags: ["Rust", "DevTools", "Performance", "Open Source", "Compilers"],
    remote: true,
    rustLevel: "CORE" as RustLevel,
    atsProvider: null,
    category: "DEV_TOOLS" as CompanyCategory,
    juniorAccessible: false,
    openSourceRepo: "https://github.com/zed-industries/zed",
  },
  {
    name: "Canonical",
    slug: "canonical",
    logoUrl: null,
    description: "The company behind Ubuntu Linux. Building open source infrastructure software for cloud, IoT, and enterprise.",
    careersUrl: "https://canonical.com/careers",
    loginUrl: null,
    tags: ["Linux", "Infrastructure", "Open Source", "Cloud", "Systems"],
    remote: true,
    rustLevel: "NONE" as RustLevel,
    atsProvider: null,
  },
  {
    name: "Datadog",
    slug: "datadog",
    logoUrl: null,
    description: "Cloud monitoring and observability platform. Engineering Rust into their high-performance data pipelines.",
    careersUrl: "https://www.datadoghq.com/careers/",
    loginUrl: "https://app.datadoghq.com",
    tags: ["Observability", "Infrastructure", "Backend", "Cloud", "Rust"],
    remote: true,
    rustLevel: "PARTIAL" as RustLevel,
    atsProvider: "Greenhouse",
  },
  {
    name: "Grafana Labs",
    slug: "grafana-labs",
    logoUrl: null,
    description: "The open and composable observability and data visualization platform. Grafana, Loki, Tempo, and more.",
    careersUrl: "https://grafana.com/about/careers/",
    loginUrl: "https://grafana.com/auth/sign-in/",
    tags: ["Observability", "Open Source", "Backend", "Infrastructure"],
    remote: true,
    rustLevel: "NONE" as RustLevel,
    atsProvider: "Greenhouse",
  },
  {
    name: "Discord",
    slug: "discord",
    logoUrl: null,
    description: "Communication platform for communities. Rewrote critical services in Rust for performance at scale.",
    careersUrl: "https://discord.com/careers",
    loginUrl: "https://discord.com/login",
    tags: ["Rust", "Backend", "Distributed Systems", "Performance"],
    remote: true,
    rustLevel: "PARTIAL" as RustLevel,
    atsProvider: "Greenhouse",
  },
  {
    name: "Fastly",
    slug: "fastly",
    logoUrl: null,
    description: "Edge cloud platform powering the world's fastest websites. Rust is used in Compute@Edge and their Varnish replacement.",
    careersUrl: "https://www.fastly.com/about/careers/",
    loginUrl: "https://manage.fastly.com",
    tags: ["Rust", "Networking", "Infrastructure", "Cloud", "Performance"],
    remote: true,
    rustLevel: "HEAVY" as RustLevel,
    atsProvider: "Lever",
    category: "NETWORKING" as CompanyCategory,
    juniorAccessible: false,
  },
  {
    name: "GitLab",
    slug: "gitlab",
    logoUrl: null,
    description: "The complete DevOps platform delivered as a single application. Fully remote company with 2,000+ employees.",
    careersUrl: "https://about.gitlab.com/jobs/",
    loginUrl: "https://gitlab.com/users/sign_in",
    tags: ["Backend", "DevTools", "Open Source", "Infrastructure"],
    remote: true,
    rustLevel: "NONE" as RustLevel,
    atsProvider: "Greenhouse",
  },
  {
    name: "Elastic",
    slug: "elastic",
    logoUrl: null,
    description: "Search, observability, and security at scale. Elasticsearch, Kibana, Beats, and Logstash.",
    careersUrl: "https://www.elastic.co/careers/",
    loginUrl: "https://cloud.elastic.co",
    tags: ["Backend", "Distributed Systems", "Databases", "Observability"],
    remote: true,
    rustLevel: "NONE" as RustLevel,
    atsProvider: "Greenhouse",
  },
  {
    name: "Sentry",
    slug: "sentry",
    logoUrl: null,
    description: "Application monitoring with full stack error tracking. Relay (ingestion layer) is written in Rust.",
    careersUrl: "https://sentry.io/careers/",
    loginUrl: "https://sentry.io/auth/login/",
    tags: ["Rust", "Observability", "Open Source", "Backend"],
    remote: true,
    rustLevel: "PARTIAL" as RustLevel,
    atsProvider: "Lever",
    category: "OBSERVABILITY" as CompanyCategory,
    juniorAccessible: false,
    openSourceRepo: "https://github.com/getsentry/relay",
  },
  {
    name: "Mozilla",
    slug: "mozilla",
    logoUrl: null,
    description: "The organization behind Firefox and the creators of Rust. Deep expertise in systems programming and browser engineering.",
    careersUrl: "https://www.mozilla.org/en-US/careers/listings/",
    loginUrl: null,
    tags: ["Rust", "Systems", "Open Source", "Security", "Compilers"],
    remote: true,
    rustLevel: "CORE" as RustLevel,
    atsProvider: "Greenhouse",
    category: "SYSTEMS" as CompanyCategory,
    juniorAccessible: false,
    openSourceRepo: "https://github.com/mozilla/gecko-dev",
  },
  {
    name: "ClickHouse",
    slug: "clickhouse",
    logoUrl: null,
    description: "The fastest and most resource-efficient real-time data warehouse. Open source with a cloud offering.",
    careersUrl: "https://clickhouse.com/company/careers",
    loginUrl: "https://clickhouse.cloud/signIn",
    tags: ["Databases", "Performance", "Backend", "Open Source", "Distributed Systems"],
    remote: true,
    rustLevel: "NONE" as RustLevel,
    atsProvider: "Greenhouse",
  },
  {
    name: "Cockroach Labs",
    slug: "cockroach-labs",
    logoUrl: null,
    description: "Distributed SQL database built for global scale. CockroachDB is the cloud-native, distributed SQL database.",
    careersUrl: "https://www.cockroachlabs.com/careers/",
    loginUrl: "https://cockroachlabs.cloud/",
    tags: ["Databases", "Distributed Systems", "Backend", "Cloud"],
    remote: true,
    rustLevel: "NONE" as RustLevel,
    atsProvider: "Lever",
  },
  {
    name: "Materialize",
    slug: "materialize",
    logoUrl: null,
    description: "Real-time data warehouse powered by streaming SQL. Built in Rust on top of Timely Dataflow.",
    careersUrl: "https://materialize.com/careers/",
    loginUrl: "https://console.materialize.com/",
    tags: ["Rust", "Databases", "Distributed Systems", "Streaming", "Performance"],
    remote: true,
    rustLevel: "CORE" as RustLevel,
    atsProvider: null,
    category: "DATABASES" as CompanyCategory,
    juniorAccessible: false,
  },
  {
    name: "Deepgram",
    slug: "deepgram",
    logoUrl: null,
    description: "AI speech recognition API built on GPU-accelerated neural networks. Core systems in Rust.",
    careersUrl: "https://deepgram.com/company/careers",
    loginUrl: "https://console.deepgram.com",
    tags: ["Rust", "AI Infra", "Backend", "Performance"],
    remote: true,
    rustLevel: "HEAVY" as RustLevel,
    atsProvider: "Lever",
  },
  {
    name: "Sourcegraph",
    slug: "sourcegraph",
    logoUrl: null,
    description: "Universal code search for every developer and company. Code intelligence platform at scale.",
    careersUrl: "https://sourcegraph.com/careers",
    loginUrl: "https://sourcegraph.com/.auth/openidconnect/login",
    tags: ["DevTools", "Backend", "Open Source", "Infrastructure"],
    remote: true,
    rustLevel: "NONE" as RustLevel,
    atsProvider: "Greenhouse",
  },
  {
    name: "Warp",
    slug: "warp",
    logoUrl: null,
    description: "The terminal for the 21st century. GPU-accelerated, built in Rust with collaborative features.",
    careersUrl: "https://www.warp.dev/careers",
    loginUrl: null,
    tags: ["Rust", "DevTools", "Performance", "Systems"],
    remote: true,
    rustLevel: "CORE" as RustLevel,
    atsProvider: null,
    category: "DEV_TOOLS" as CompanyCategory,
    juniorAccessible: false,
  },
  {
    name: "Hetzner",
    slug: "hetzner",
    logoUrl: null,
    description: "German cloud hosting and data center company offering affordable, high-performance dedicated servers and cloud VMs.",
    careersUrl: "https://www.hetzner.com/unternehmen/jobs/",
    loginUrl: "https://accounts.hetzner.com",
    tags: ["Infrastructure", "Cloud", "Linux", "Networking"],
    remote: false,
    rustLevel: "NONE" as RustLevel,
    atsProvider: null,
  },
  {
    name: "JetBrains",
    slug: "jetbrains",
    logoUrl: null,
    description: "Makers of IntelliJ IDEA, CLion, RustRover, and 15+ developer tools. Deep investment in Rust tooling.",
    careersUrl: "https://www.jetbrains.com/careers/jobs/",
    loginUrl: "https://account.jetbrains.com",
    tags: ["DevTools", "Rust", "Compilers", "Backend"],
    remote: true,
    rustLevel: "PARTIAL" as RustLevel,
    atsProvider: "SmartRecruiters",
  },
  {
    name: "Vercel",
    slug: "vercel",
    logoUrl: null,
    description: "Frontend cloud platform for developers. Infrastructure team uses Rust in performance-critical components.",
    careersUrl: "https://vercel.com/careers",
    loginUrl: "https://vercel.com/login",
    tags: ["Infrastructure", "DevTools", "Cloud", "Backend"],
    remote: true,
    rustLevel: "PARTIAL" as RustLevel,
    atsProvider: "Greenhouse",
  },
  {
    name: "Mux",
    slug: "mux",
    logoUrl: null,
    description: "Video infrastructure for developers. APIs for video hosting, streaming, and real-time analytics.",
    careersUrl: "https://www.mux.com/jobs",
    loginUrl: "https://dashboard.mux.com",
    tags: ["Backend", "Infrastructure", "Distributed Systems", "Performance"],
    remote: true,
    rustLevel: "NONE" as RustLevel,
    atsProvider: "Lever",
  },
  {
    name: "Timescale",
    slug: "timescale",
    logoUrl: null,
    description: "PostgreSQL for time-series data. TimescaleDB is the leading open-source time-series SQL database.",
    careersUrl: "https://www.timescale.com/careers",
    loginUrl: "https://console.cloud.timescale.com",
    tags: ["Databases", "Open Source", "Backend", "Distributed Systems"],
    remote: true,
    rustLevel: "NONE" as RustLevel,
    atsProvider: "Lever",
  },
  {
    name: "Hugging Face",
    slug: "hugging-face",
    logoUrl: null,
    description: "The AI community building the future. ML model hosting, datasets, and inference infrastructure. Candle ML framework in Rust.",
    careersUrl: "https://apply.workable.com/huggingface/",
    loginUrl: "https://huggingface.co/login",
    tags: ["Rust", "AI Infra", "Open Source", "Backend", "Infrastructure"],
    remote: true,
    rustLevel: "PARTIAL" as RustLevel,
    atsProvider: "Workable",
  },
  {
    name: "Ferrous Systems",
    slug: "ferrous-systems",
    logoUrl: null,
    description: "The leading Rust consulting and training company. Creators of Ferrocene, the qualified Rust toolchain.",
    careersUrl: "https://ferrous-systems.com/",
    loginUrl: null,
    tags: ["Rust", "Systems", "Compilers", "Open Source"],
    remote: true,
    rustLevel: "CORE" as RustLevel,
    atsProvider: null,
    category: "COMPILERS" as CompanyCategory,
    juniorAccessible: false,
  },
  {
    name: "Red Hat",
    slug: "red-hat",
    logoUrl: null,
    description: "The world's leading provider of enterprise open source solutions. Significant Rust investment in system-level projects.",
    careersUrl: "https://www.redhat.com/en/jobs",
    loginUrl: "https://sso.redhat.com",
    tags: ["Linux", "Open Source", "Systems", "Infrastructure", "Security"],
    remote: true,
    rustLevel: "PARTIAL" as RustLevel,
    atsProvider: "Workday",
  },
  {
    name: "Turing",
    slug: "turing",
    logoUrl: null,
    description: "Remote engineering jobs platform connecting developers with top US tech companies. Fully remote.",
    careersUrl: "https://www.turing.com/jobs",
    loginUrl: "https://engineers.turing.com",
    tags: ["Backend", "Infrastructure", "Remote"],
    remote: true,
    rustLevel: "NONE" as RustLevel,
    atsProvider: null,
  },
  {
    name: "Tokio",
    slug: "tokio-rs",
    logoUrl: null,
    description: "The async runtime for Rust. Tokio Company is the commercial entity behind the tokio async runtime and Tower ecosystem.",
    careersUrl: "https://tokio.rs",
    loginUrl: null,
    tags: ["Rust", "Open Source", "Backend", "Systems", "Networking"],
    remote: true,
    rustLevel: "CORE" as RustLevel,
    atsProvider: null,
  },
  {
    name: "Temporal",
    slug: "temporal",
    logoUrl: null,
    description: "Durable execution platform for building reliable distributed applications. Open source workflow orchestration.",
    careersUrl: "https://temporal.io/careers",
    loginUrl: "https://cloud.temporal.io",
    tags: ["Distributed Systems", "Backend", "Open Source", "Infrastructure"],
    remote: true,
    rustLevel: "NONE" as RustLevel,
    atsProvider: "Greenhouse",
  },
  {
    name: "Tailscale",
    slug: "tailscale",
    logoUrl: null,
    description: "Zero-config VPN built on WireGuard. Making networking easy for developers and enterprises.",
    careersUrl: "https://tailscale.com/careers/",
    loginUrl: "https://login.tailscale.com",
    tags: ["Networking", "Security", "Infrastructure", "Backend"],
    remote: true,
    rustLevel: "NONE" as RustLevel,
    atsProvider: null,
  },
  {
    name: "1Password",
    slug: "1password",
    logoUrl: null,
    description: "Password manager and secrets management. Significant portions of their cross-platform client and infrastructure use Rust.",
    careersUrl: "https://1password.com/careers",
    loginUrl: "https://my.1password.com",
    tags: ["Rust", "Security", "Backend", "Systems"],
    remote: true,
    rustLevel: "HEAVY" as RustLevel,
    atsProvider: "Lever",
    category: "SECURITY" as CompanyCategory,
    juniorAccessible: false,
  },
  {
    name: "Parity Technologies",
    slug: "parity-technologies",
    logoUrl: null,
    description: "Core Ethereum and blockchain infrastructure company. Substrate (Polkadot framework) is written in Rust.",
    careersUrl: "https://www.parity.io/jobs",
    loginUrl: null,
    tags: ["Rust", "Distributed Systems", "Systems", "Open Source"],
    remote: true,
    rustLevel: "CORE" as RustLevel,
    atsProvider: null,
    category: "WEB3" as CompanyCategory,
    juniorAccessible: false,
    openSourceRepo: "https://github.com/paritytech/polkadot-sdk",
  },
  {
    name: "Palantir",
    slug: "palantir",
    logoUrl: null,
    description: "Data analytics and intelligence platform for governments and enterprises. Large-scale distributed systems.",
    careersUrl: "https://jobs.lever.co/palantir",
    loginUrl: null,
    tags: ["Backend", "Distributed Systems", "Infrastructure", "Security"],
    remote: false,
    rustLevel: "NONE" as RustLevel,
    atsProvider: "Greenhouse",
  },
  {
    name: "Databricks",
    slug: "databricks",
    logoUrl: null,
    description: "Unified analytics platform for data engineering, data science, and machine learning at scale.",
    careersUrl: "https://www.databricks.com/company/careers",
    loginUrl: "https://accounts.cloud.databricks.com",
    tags: ["Backend", "Distributed Systems", "AI Infra", "Cloud", "Databases"],
    remote: true,
    rustLevel: "NONE" as RustLevel,
    atsProvider: "Greenhouse",
  },
  {
    name: "HashiCorp",
    slug: "hashicorp",
    logoUrl: null,
    description: "Infrastructure automation software (Terraform, Vault, Consul, Nomad). Now part of IBM.",
    careersUrl: "https://www.hashicorp.com/careers",
    loginUrl: "https://app.terraform.io",
    tags: ["Infrastructure", "DevTools", "Open Source", "Cloud", "Security"],
    remote: true,
    rustLevel: "NONE" as RustLevel,
    atsProvider: "Greenhouse",
  },
  {
    name: "AWS",
    slug: "aws",
    logoUrl: null,
    description: "Amazon Web Services — cloud computing. Heavy Rust adoption in Firecracker, Bottlerocket, and other services.",
    careersUrl: "https://aws.amazon.com/careers/",
    loginUrl: "https://console.aws.amazon.com",
    tags: ["Rust", "Cloud", "Infrastructure", "Distributed Systems", "Systems"],
    remote: true,
    rustLevel: "HEAVY" as RustLevel,
    atsProvider: "Amazon Jobs",
  },
  {
    name: "Ardan Labs",
    slug: "ardan-labs",
    logoUrl: null,
    description: "Elite Go and Rust training and consulting company. Known for Bill Kennedy's Ultimate Go course.",
    careersUrl: "https://www.ardanlabs.com/",
    loginUrl: null,
    tags: ["Rust", "Backend", "Systems", "Open Source"],
    remote: true,
    rustLevel: "PARTIAL" as RustLevel,
    atsProvider: null,
  },
  {
    name: "Neon",
    slug: "neon",
    logoUrl: null,
    description: "Serverless Postgres with branching. The storage layer and compute node are built in Rust.",
    careersUrl: "https://neon.tech/careers",
    loginUrl: "https://console.neon.tech",
    tags: ["Rust", "Databases", "Cloud", "Open Source", "Performance"],
    remote: true,
    rustLevel: "CORE" as RustLevel,
    atsProvider: "Lever",
    category: "DATABASES" as CompanyCategory,
    juniorAccessible: true,
    openSourceRepo: "https://github.com/neondatabase/neon",
  },
  {
    name: "Tremor",
    slug: "tremor",
    logoUrl: null,
    description: "Event processing system written in Rust for wayfair-scale data pipelines. Now an open source CNCF project.",
    careersUrl: "https://www.tremor.rs",
    loginUrl: null,
    tags: ["Rust", "Distributed Systems", "Backend", "Open Source", "Observability"],
    remote: true,
    rustLevel: "CORE" as RustLevel,
    atsProvider: null,
  },
  {
    name: "Figma",
    slug: "figma",
    logoUrl: null,
    description: "Collaborative design platform. Uses Rust for WebAssembly performance-critical rendering components.",
    careersUrl: "https://www.figma.com/careers/",
    loginUrl: "https://figma.com/login",
    tags: ["Rust", "Backend", "DevTools", "Performance"],
    remote: true,
    rustLevel: "PARTIAL" as RustLevel,
    atsProvider: "Greenhouse",
  },
  {
    name: "Linear",
    slug: "linear",
    logoUrl: null,
    description: "The issue tracker that makes software development faster. Known for speed, design, and developer experience.",
    careersUrl: "https://linear.app/careers",
    loginUrl: "https://linear.app/login",
    tags: ["DevTools", "Backend", "Performance"],
    remote: true,
    rustLevel: "NONE" as RustLevel,
    atsProvider: null,
  },
  {
    name: "Notion",
    slug: "notion",
    logoUrl: null,
    description: "All-in-one workspace for notes, docs, and collaboration. Strong backend and infrastructure teams.",
    careersUrl: "https://www.notion.so/careers",
    loginUrl: "https://www.notion.so/login",
    tags: ["Backend", "Infrastructure", "Distributed Systems"],
    remote: false,
    rustLevel: "NONE" as RustLevel,
    atsProvider: "Greenhouse",
  },
  {
    name: "PlanetScale",
    slug: "planetscale",
    logoUrl: null,
    description: "Serverless MySQL platform powered by Vitess. Horizontally scalable database for modern applications.",
    careersUrl: "https://planetscale.com/careers",
    loginUrl: "https://app.planetscale.com",
    tags: ["Databases", "Cloud", "Backend", "Distributed Systems"],
    remote: true,
    rustLevel: "NONE" as RustLevel,
    atsProvider: "Lever",
  },
  {
    name: "Stripe",
    slug: "stripe",
    logoUrl: null,
    description: "Financial infrastructure for the internet. Massive distributed systems powering global payments.",
    careersUrl: "https://stripe.com/jobs",
    loginUrl: "https://dashboard.stripe.com/login",
    tags: ["Backend", "Distributed Systems", "Security", "Infrastructure"],
    remote: true,
    rustLevel: "NONE" as RustLevel,
    atsProvider: "Lever",
  },
  {
    name: "Shopify",
    slug: "shopify",
    logoUrl: null,
    description: "Commerce platform for millions of businesses worldwide. Large engineering org with strong remote culture.",
    careersUrl: "https://www.shopify.com/careers",
    loginUrl: "https://accounts.shopify.com",
    tags: ["Backend", "Infrastructure", "Distributed Systems", "Cloud"],
    remote: true,
    rustLevel: "NONE" as RustLevel,
    atsProvider: "Greenhouse",
  },
  {
    name: "Apple (SEAR)",
    slug: "apple-sear",
    logoUrl: null,
    description: "Apple's Swift and Rust ecosystem team. Working on language runtimes, compilers, and systems programming.",
    careersUrl: "https://jobs.apple.com",
    loginUrl: null,
    tags: ["Rust", "Compilers", "Systems", "Performance"],
    remote: false,
    rustLevel: "PARTIAL" as RustLevel,
    atsProvider: "iCIMS",
  },
  {
    name: "Google (Android)",
    slug: "google-android",
    logoUrl: null,
    description: "The Android platform team is adopting Rust as a memory-safe system language alongside C++.",
    careersUrl: "https://careers.google.com",
    loginUrl: null,
    tags: ["Rust", "Systems", "Linux", "Security", "Performance"],
    remote: false,
    rustLevel: "PARTIAL" as RustLevel,
    atsProvider: "Google Hire",
  },
  {
    name: "Microsoft (RUST)",
    slug: "microsoft-rust",
    logoUrl: null,
    description: "Microsoft has adopted Rust extensively in Windows, Azure, and their security-critical systems.",
    careersUrl: "https://careers.microsoft.com",
    loginUrl: null,
    tags: ["Rust", "Systems", "Cloud", "Security", "Windows"],
    remote: true,
    rustLevel: "HEAVY" as RustLevel,
    atsProvider: "Microsoft",
  },
  {
    name: "Signal",
    slug: "signal",
    logoUrl: null,
    description: "Encrypted messaging app with a mission to build private communication tools. Uses Rust in signal-zkgroup and other cryptographic libraries.",
    careersUrl: "https://signal.org/workworkwork/",
    loginUrl: null,
    tags: ["Rust", "Security", "Backend", "Open Source", "Systems"],
    remote: true,
    rustLevel: "PARTIAL" as RustLevel,
    atsProvider: null,
  },
  {
    name: "Dropbox",
    slug: "dropbox",
    logoUrl: null,
    description: "Cloud storage and collaboration company. Rewrote their sync engine from Python to Rust.",
    careersUrl: "https://jobs.dropbox.com",
    loginUrl: "https://www.dropbox.com/login",
    tags: ["Rust", "Systems", "Backend", "Distributed Systems"],
    remote: true,
    rustLevel: "PARTIAL" as RustLevel,
    atsProvider: "Greenhouse",
  },
  {
    name: "Svix",
    slug: "svix",
    logoUrl: null,
    description: "Webhooks as a service. The enterprise-grade webhook service for developers. Built in Rust.",
    careersUrl: "https://www.svix.com/careers/",
    loginUrl: "https://dashboard.svix.com",
    tags: ["Rust", "Backend", "Infrastructure", "Open Source"],
    remote: true,
    rustLevel: "CORE" as RustLevel,
    atsProvider: null,
    category: "DEV_TOOLS" as CompanyCategory,
    juniorAccessible: true,
    openSourceRepo: "https://github.com/svix/svix-webhooks",
  },
  {
    name: "Embark Studios",
    slug: "embark-studios",
    logoUrl: null,
    description: "Stockholm-based game studio pushing Rust adoption in game development. Creators of rust-gpu and other open source tools.",
    careersUrl: "https://www.embark-studios.com/jobs",
    loginUrl: null,
    tags: ["Rust", "Open Source", "Systems", "Performance"],
    remote: false,
    rustLevel: "CORE" as RustLevel,
    atsProvider: null,
  },
]

// When each company's hiring status was last manually verified.
// Used to surface freshness in the UI ("verified X days ago").
const LAST_VERIFIED: Record<string, Date> = {
  "cloudflare":         new Date("2026-05-15"),
  "fly-io":             new Date("2026-05-18"),
  "oxide-computer":     new Date("2026-05-22"),
  "turso":              new Date("2026-05-20"),
  "zed-industries":     new Date("2026-05-19"),
  "canonical":          new Date("2026-05-10"),
  "datadog":            new Date("2026-05-12"),
  "grafana-labs":       new Date("2026-05-08"),
  "discord":            new Date("2026-05-14"),
  "fastly":             new Date("2026-05-16"),
  "gitlab":             new Date("2026-05-01"),
  "elastic":            new Date("2026-05-05"),
  "sentry":             new Date("2026-05-17"),
  "mozilla":            new Date("2026-05-21"),
  "clickhouse":         new Date("2026-05-13"),
  "cockroach-labs":     new Date("2026-05-03"),
  "materialize":        new Date("2026-05-25"),
  "deepgram":           new Date("2026-05-11"),
  "sourcegraph":        new Date("2026-04-20"),
  "warp":               new Date("2026-05-23"),
  "hetzner":            new Date("2026-04-15"),
  "jetbrains":          new Date("2026-05-07"),
  "vercel":             new Date("2026-05-09"),
  "mux":                new Date("2026-04-28"),
  "timescale":          new Date("2026-04-25"),
  "hugging-face":       new Date("2026-05-15"),
  "ferrous-systems":    new Date("2026-05-24"),
  "red-hat":            new Date("2026-04-30"),
  "turing":             new Date("2026-05-02"),
  "tokio-rs":           new Date("2026-04-01"),
  "temporal":           new Date("2026-05-06"),
  "tailscale":          new Date("2026-05-04"),
  "1password":          new Date("2026-05-20"),
  "parity-technologies":new Date("2026-05-22"),
  "palantir":           new Date("2026-04-10"),
  "databricks":         new Date("2026-04-22"),
  "hashicorp":          new Date("2026-04-18"),
  "aws":                new Date("2026-05-18"),
  "ardan-labs":         new Date("2026-05-01"),
  "neon":               new Date("2026-05-26"),
  "tremor":             new Date("2026-03-15"),
  "figma":              new Date("2026-05-15"),
  "linear":             new Date("2026-05-10"),
  "notion":             new Date("2026-04-25"),
  "planetscale":        new Date("2026-04-15"),
  "stripe":             new Date("2026-05-10"),
  "shopify":            new Date("2026-05-05"),
  "apple-sear":         new Date("2026-05-20"),
  "google-android":     new Date("2026-05-15"),
  "microsoft-rust":     new Date("2026-05-18"),
  "signal":             new Date("2026-04-20"),
  "dropbox":            new Date("2026-04-10"),
  "svix":               new Date("2026-05-24"),
  "embark-studios":     new Date("2026-04-01"),
}

async function main() {
  console.log("Seeding database...")

  for (const company of companies) {
    const data = { ...company, lastHiringCheckAt: LAST_VERIFIED[company.slug] ?? null }
    await prisma.company.upsert({
      where: { slug: company.slug },
      create: data,
      update: data,
    })
    console.log(`  ✓ ${company.name}`)
  }

  const count = await prisma.company.count()
  console.log(`\nDone! ${count} companies in database.`)

  // ─── Seed curated opportunities ─────────────────────────────────────────────
  console.log("\nSeeding curated opportunities...")

  type OpportunitySeed = {
    companySlug: string
    title: string
    sourceUrl: string
    tags: string[]
    rustSignal: RustSignal
    experienceLevel: ExperienceLevel
    isRemote: boolean
    isJuniorFriendly: boolean
    hasOssPath: boolean
    baseQualityScore: number
    location?: string
  }

  const seedOpportunities: OpportunitySeed[] = [
    {
      companySlug: "svix",
      title: "Software Engineer (Rust)",
      sourceUrl: "https://www.svix.com/careers/",
      tags: ["Rust", "Backend", "Open Source"],
      rustSignal: "CORE" as RustSignal,
      experienceLevel: "JUNIOR" as ExperienceLevel,
      isRemote: true,
      isJuniorFriendly: true,
      hasOssPath: true,
      baseQualityScore: 100,
    },
    {
      companySlug: "turso",
      title: "Backend Engineer (Rust)",
      sourceUrl: "https://turso.tech/careers",
      tags: ["Rust", "Databases", "Open Source"],
      rustSignal: "CORE" as RustSignal,
      experienceLevel: "JUNIOR" as ExperienceLevel,
      isRemote: true,
      isJuniorFriendly: true,
      hasOssPath: true,
      baseQualityScore: 100,
    },
    {
      companySlug: "neon",
      title: "Systems Engineer (Rust)",
      sourceUrl: "https://neon.tech/careers",
      tags: ["Rust", "Databases", "PostgreSQL"],
      rustSignal: "CORE" as RustSignal,
      experienceLevel: "MID" as ExperienceLevel,
      isRemote: true,
      isJuniorFriendly: true,
      hasOssPath: true,
      baseQualityScore: 100,
    },
    {
      companySlug: "zed-industries",
      title: "Rust Engineer",
      sourceUrl: "https://zed.dev/jobs",
      tags: ["Rust", "DevTools", "Open Source"],
      rustSignal: "CORE" as RustSignal,
      experienceLevel: "MID" as ExperienceLevel,
      isRemote: true,
      isJuniorFriendly: false,
      hasOssPath: true,
      baseQualityScore: 90,
    },
    {
      companySlug: "mozilla",
      title: "Rust Engineer, Firefox/Servo",
      sourceUrl: "https://www.mozilla.org/en-US/careers/listings/",
      tags: ["Rust", "Systems", "Open Source", "Compilers"],
      rustSignal: "CORE" as RustSignal,
      experienceLevel: "MID" as ExperienceLevel,
      isRemote: true,
      isJuniorFriendly: false,
      hasOssPath: true,
      baseQualityScore: 90,
    },
    {
      companySlug: "warp",
      title: "Software Engineer, Rust Terminal",
      sourceUrl: "https://www.warp.dev/careers",
      tags: ["Rust", "DevTools", "Systems"],
      rustSignal: "CORE" as RustSignal,
      experienceLevel: "MID" as ExperienceLevel,
      isRemote: true,
      isJuniorFriendly: false,
      hasOssPath: false,
      baseQualityScore: 86,
    },
    {
      companySlug: "sentry",
      title: "Software Engineer, Rust (Relay)",
      sourceUrl: "https://sentry.io/careers/",
      tags: ["Rust", "Observability", "Open Source"],
      rustSignal: "HIGH" as RustSignal,
      experienceLevel: "MID" as ExperienceLevel,
      isRemote: true,
      isJuniorFriendly: false,
      hasOssPath: true,
      baseQualityScore: 80,
    },
    {
      companySlug: "parity-technologies",
      title: "Rust Developer, Substrate/Polkadot",
      sourceUrl: "https://www.parity.io/jobs",
      tags: ["Rust", "Distributed Systems", "Open Source"],
      rustSignal: "CORE" as RustSignal,
      experienceLevel: "SENIOR" as ExperienceLevel,
      isRemote: true,
      isJuniorFriendly: false,
      hasOssPath: true,
      baseQualityScore: 77,
    },
    {
      companySlug: "fly-io",
      title: "Infrastructure Engineer (Rust)",
      sourceUrl: "https://fly.io/jobs/",
      tags: ["Rust", "Infrastructure", "Cloud"],
      rustSignal: "HIGH" as RustSignal,
      experienceLevel: "MID" as ExperienceLevel,
      isRemote: true,
      isJuniorFriendly: false,
      hasOssPath: false,
      baseQualityScore: 76,
    },
    {
      companySlug: "1password",
      title: "Software Engineer, Rust",
      sourceUrl: "https://1password.com/careers",
      tags: ["Rust", "Security", "Backend"],
      rustSignal: "HIGH" as RustSignal,
      experienceLevel: "MID" as ExperienceLevel,
      isRemote: true,
      isJuniorFriendly: false,
      hasOssPath: false,
      baseQualityScore: 76,
    },
    {
      companySlug: "fastly",
      title: "Software Engineer, Compute@Edge",
      sourceUrl: "https://www.fastly.com/about/careers/",
      tags: ["Rust", "Networking", "Infrastructure"],
      rustSignal: "HIGH" as RustSignal,
      experienceLevel: "MID" as ExperienceLevel,
      isRemote: true,
      isJuniorFriendly: false,
      hasOssPath: false,
      baseQualityScore: 76,
    },
    {
      companySlug: "materialize",
      title: "Database Engineer (Rust)",
      sourceUrl: "https://materialize.com/careers/",
      tags: ["Rust", "Databases", "Distributed Systems"],
      rustSignal: "CORE" as RustSignal,
      experienceLevel: "SENIOR" as ExperienceLevel,
      isRemote: true,
      isJuniorFriendly: false,
      hasOssPath: false,
      baseQualityScore: 73,
    },
    {
      companySlug: "ferrous-systems",
      title: "Rust Consultant / Engineer",
      sourceUrl: "https://ferrous-systems.com/",
      tags: ["Rust", "Systems", "Compilers"],
      rustSignal: "CORE" as RustSignal,
      experienceLevel: "SENIOR" as ExperienceLevel,
      isRemote: true,
      isJuniorFriendly: false,
      hasOssPath: false,
      baseQualityScore: 73,
    },
    {
      companySlug: "oxide-computer",
      title: "Systems Software Engineer",
      sourceUrl: "https://oxide.computer/careers",
      tags: ["Rust", "Systems", "Hardware"],
      rustSignal: "CORE" as RustSignal,
      experienceLevel: "SENIOR" as ExperienceLevel,
      isRemote: false,
      isJuniorFriendly: false,
      hasOssPath: false,
      location: "San Francisco, CA (on-site)",
      baseQualityScore: 65,
    },
    {
      companySlug: "cloudflare",
      title: "Systems Engineer, Rust Networking",
      sourceUrl: "https://www.cloudflare.com/careers/jobs/",
      tags: ["Rust", "Networking", "Infrastructure"],
      rustSignal: "HIGH" as RustSignal,
      experienceLevel: "SENIOR" as ExperienceLevel,
      isRemote: true,
      isJuniorFriendly: false,
      hasOssPath: false,
      baseQualityScore: 63,
    },
  ]

  for (const opp of seedOpportunities) {
    const company = await prisma.company.findUnique({ where: { slug: opp.companySlug } })
    if (!company) {
      console.log(`  ⚠ Skip: unknown company slug "${opp.companySlug}"`)
      continue
    }

    const existing = await prisma.opportunity.findFirst({
      where: { source: "CURATED" as OpportunitySource, companyId: company.id },
    })
    if (existing) {
      console.log(`  ↩ Skip (exists): ${opp.title} @ ${company.name}`)
      continue
    }

    const { companySlug: _, ...data } = opp
    await prisma.opportunity.create({
      data: {
        ...data,
        source: "CURATED" as OpportunitySource,
        companyId: company.id,
        companyName: company.name,
      },
    })
    console.log(`  ✓ ${opp.title} @ ${company.name}`)
  }

  const oppCount = await prisma.opportunity.count()
  console.log(`\nDone! ${oppCount} opportunities in database.`)
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
