// Original fictional companies — Rust ecosystem / infra / AI infra
window.COMPANIES = [
  {
    id: "vermilion",
    name: "Vermilion Labs",
    domain: "vermilion.dev",
    initials: "VL",
    color: "oklch(0.72 0.16 45)",
    desc: "Distributed query engine for petabyte-scale event data.",
    location: "Remote (Global)",
    size: "23",
    funding: "Series A",
    comp: "$210–$280k + 0.4–0.9%",
    tags: ["rust", "distributed-systems", "databases"],
    category: "Infrastructure",
    hiring: "actively-hiring",
    openings: 7,
    status: "applied",
    lastActivity: "2d",
    followup: true,
    note: "Recruiter call scheduled Thu — prep async deep-dive."
  },
  {
    id: "halcyon",
    name: "Halcyon",
    domain: "halcyon.run",
    initials: "HA",
    color: "oklch(0.68 0.14 240)",
    desc: "AI inference runtime — sub-ms cold starts on bare metal.",
    location: "Remote (US/EU)",
    size: "12",
    funding: "Seed",
    comp: "$190–$240k + 1.0–1.8%",
    tags: ["rust", "ai-infra", "wasm"],
    category: "AI Infra",
    hiring: "actively-hiring",
    openings: 4,
    status: "interviewing",
    lastActivity: "5h",
    followup: true,
    note: "Onsite next Tuesday. Reach out to Mira about systems round."
  },
  {
    id: "northwind",
    name: "Northwind Systems",
    domain: "northwind.io",
    initials: "NS",
    color: "oklch(0.70 0.13 165)",
    desc: "Storage-class memory abstraction for high-throughput services.",
    location: "Remote (Americas)",
    size: "48",
    funding: "Series B",
    comp: "$240–$320k + 0.2–0.4%",
    tags: ["rust", "storage", "kernel"],
    category: "Infrastructure",
    hiring: "selective",
    openings: 2,
    status: "saved",
    lastActivity: "1w",
    followup: false,
    note: ""
  },
  {
    id: "ferris-cloud",
    name: "Ferris Cloud",
    domain: "ferris.cloud",
    initials: "FC",
    color: "oklch(0.72 0.16 45)",
    desc: "Edge functions written in Rust, deployed in under 200ms globally.",
    location: "Remote (Global)",
    size: "67",
    funding: "Series B",
    comp: "$220–$300k + 0.15–0.35%",
    tags: ["rust", "edge", "platform"],
    category: "Platform",
    hiring: "actively-hiring",
    openings: 11,
    status: "applied",
    lastActivity: "4d",
    followup: false,
    note: "Take-home submitted. Awaiting review (median ~6 days)."
  },
  {
    id: "obsidian-net",
    name: "Obsidian Net",
    domain: "obsidian.net",
    initials: "ON",
    color: "oklch(0.62 0.11 285)",
    desc: "Programmable networking fabric for AI training clusters.",
    location: "Remote (US)",
    size: "31",
    funding: "Series A",
    comp: "$230–$310k + 0.3–0.7%",
    tags: ["rust", "networking", "ai-infra"],
    category: "AI Infra",
    hiring: "actively-hiring",
    openings: 5,
    status: "saved",
    lastActivity: "3d",
    followup: false,
    note: ""
  },
  {
    id: "tempo-db",
    name: "Tempo DB",
    domain: "tempo.db",
    initials: "TD",
    color: "oklch(0.70 0.13 195)",
    desc: "Time-series database engineered for sub-millisecond reads.",
    location: "Remote (EU)",
    size: "19",
    funding: "Seed",
    comp: "$170–$220k + 0.8–1.5%",
    tags: ["rust", "databases", "time-series"],
    category: "Databases",
    hiring: "actively-hiring",
    openings: 3,
    status: "none",
    lastActivity: "1d",
    followup: false,
    note: ""
  },
  {
    id: "kestrel",
    name: "Kestrel Security",
    domain: "kestrel.security",
    initials: "KS",
    color: "oklch(0.66 0.18 22)",
    desc: "Memory-safe runtime sandboxing for high-risk workloads.",
    location: "Remote (Global)",
    size: "42",
    funding: "Series A",
    comp: "$220–$290k + 0.25–0.6%",
    tags: ["rust", "security", "sandboxing"],
    category: "Security",
    hiring: "selective",
    openings: 1,
    status: "rejected",
    lastActivity: "3w",
    followup: false,
    note: "Pushed back on systems round — try again in Q3."
  },
  {
    id: "pinion",
    name: "Pinion",
    domain: "pinion.engineering",
    initials: "PI",
    color: "oklch(0.74 0.14 95)",
    desc: "Build system for monorepos with deterministic remote execution.",
    location: "Remote (US/EU)",
    size: "26",
    funding: "Series A",
    comp: "$200–$270k + 0.4–0.8%",
    tags: ["rust", "devtools", "build-systems"],
    category: "Developer Tools",
    hiring: "actively-hiring",
    openings: 6,
    status: "saved",
    lastActivity: "6d",
    followup: false,
    note: ""
  },
  {
    id: "axiom-runtime",
    name: "Axiom Runtime",
    domain: "axiom.run",
    initials: "AX",
    color: "oklch(0.68 0.14 240)",
    desc: "Deterministic actor runtime for fault-tolerant backends.",
    location: "Remote (Global)",
    size: "14",
    funding: "Seed",
    comp: "$180–$240k + 1.0–2.0%",
    tags: ["rust", "distributed-systems", "actor-model"],
    category: "Infrastructure",
    hiring: "actively-hiring",
    openings: 4,
    status: "interviewing",
    lastActivity: "12h",
    followup: true,
    note: "Final round Mon. Prep: distributed consensus + Raft pitfalls."
  },
  {
    id: "lumen-ai",
    name: "Lumen AI",
    domain: "lumen.ai",
    initials: "LU",
    color: "oklch(0.70 0.13 320)",
    desc: "Open-weight model hosting with hardware-aware schedulers.",
    location: "Remote (US/EU)",
    size: "55",
    funding: "Series B",
    comp: "$240–$330k + 0.2–0.5%",
    tags: ["rust", "ai-infra", "ml-systems"],
    category: "AI Infra",
    hiring: "actively-hiring",
    openings: 9,
    status: "none",
    lastActivity: "2d",
    followup: false,
    note: ""
  },
  {
    id: "stratum",
    name: "Stratum",
    domain: "stratum.engineering",
    initials: "ST",
    color: "oklch(0.70 0.13 165)",
    desc: "Observability pipeline that ingests trillions of spans per day.",
    location: "Remote (Global)",
    size: "78",
    funding: "Series C",
    comp: "$250–$340k + 0.1–0.25%",
    tags: ["rust", "observability", "distributed-systems"],
    category: "Infrastructure",
    hiring: "actively-hiring",
    openings: 14,
    status: "applied",
    lastActivity: "1d",
    followup: true,
    note: "Recruiter ping — schedule intro this week."
  },
  {
    id: "quill-systems",
    name: "Quill Systems",
    domain: "quill.systems",
    initials: "QS",
    color: "oklch(0.72 0.16 45)",
    desc: "Embedded Rust toolchain for safety-critical hardware.",
    location: "Remote (EU)",
    size: "21",
    funding: "Series A",
    comp: "$180–$230k + 0.5–1.0%",
    tags: ["rust", "embedded", "safety-critical"],
    category: "Embedded",
    hiring: "selective",
    openings: 2,
    status: "saved",
    lastActivity: "2w",
    followup: false,
    note: ""
  },
  {
    id: "monolith-zero",
    name: "Monolith Zero",
    domain: "monolith0.dev",
    initials: "MZ",
    color: "oklch(0.62 0.11 285)",
    desc: "Single-binary deploy platform built around capability-based auth.",
    location: "Remote (Americas)",
    size: "9",
    funding: "Pre-seed",
    comp: "$160–$210k + 1.5–3.0%",
    tags: ["rust", "platform", "security"],
    category: "Platform",
    hiring: "no-openings",
    openings: 0,
    status: "none",
    lastActivity: "1m",
    followup: false,
    note: ""
  },
  {
    id: "anchor-protocol",
    name: "Anchor Protocol",
    domain: "anchor.dev",
    initials: "AP",
    color: "oklch(0.70 0.13 195)",
    desc: "Coordination primitives for multi-region stateful services.",
    location: "Remote (Global)",
    size: "33",
    funding: "Series A",
    comp: "$210–$280k + 0.4–0.8%",
    tags: ["rust", "distributed-systems", "consensus"],
    category: "Infrastructure",
    hiring: "actively-hiring",
    openings: 5,
    status: "saved",
    lastActivity: "5d",
    followup: false,
    note: ""
  },
  {
    id: "drift-labs",
    name: "Drift Labs",
    domain: "drift.lab",
    initials: "DL",
    color: "oklch(0.74 0.14 95)",
    desc: "Latency-deterministic message bus for low-latency trading.",
    location: "Remote (US)",
    size: "17",
    funding: "Seed",
    comp: "$220–$310k + 0.6–1.2%",
    tags: ["rust", "low-latency", "messaging"],
    category: "Infrastructure",
    hiring: "actively-hiring",
    openings: 3,
    status: "applied",
    lastActivity: "6d",
    followup: false,
    note: "Submitted via referral — Jonas in DMs."
  },
  {
    id: "spire",
    name: "Spire",
    domain: "spire.engineering",
    initials: "SP",
    color: "oklch(0.68 0.14 240)",
    desc: "Programmable feature store with first-class lineage.",
    location: "Remote (US/EU)",
    size: "29",
    funding: "Series A",
    comp: "$210–$280k + 0.3–0.6%",
    tags: ["rust", "ml-systems", "data"],
    category: "AI Infra",
    hiring: "actively-hiring",
    openings: 4,
    status: "none",
    lastActivity: "9h",
    followup: false,
    note: ""
  },
  {
    id: "stoa",
    name: "Stoa",
    domain: "stoa.cloud",
    initials: "SO",
    color: "oklch(0.70 0.13 320)",
    desc: "Capability-typed service mesh — no sidecars, no YAML.",
    location: "Remote (Global)",
    size: "8",
    funding: "Pre-seed",
    comp: "$170–$220k + 1.5–3.0%",
    tags: ["rust", "networking", "platform"],
    category: "Platform",
    hiring: "actively-hiring",
    openings: 2,
    status: "none",
    lastActivity: "4h",
    followup: false,
    note: ""
  },
  {
    id: "argent",
    name: "Argent",
    domain: "argent.tools",
    initials: "AR",
    color: "oklch(0.66 0.18 22)",
    desc: "Type-safe runtime introspection for production Rust services.",
    location: "Remote (EU)",
    size: "11",
    funding: "Seed",
    comp: "$180–$230k + 1.0–2.0%",
    tags: ["rust", "devtools", "observability"],
    category: "Developer Tools",
    hiring: "selective",
    openings: 1,
    status: "saved",
    lastActivity: "2w",
    followup: false,
    note: ""
  },
  {
    id: "veridian",
    name: "Veridian",
    domain: "veridian.compute",
    initials: "VE",
    color: "oklch(0.70 0.13 165)",
    desc: "GPU scheduling and bin-packing for sovereign AI clusters.",
    location: "Remote (Global)",
    size: "38",
    funding: "Series A",
    comp: "$240–$320k + 0.3–0.6%",
    tags: ["rust", "ai-infra", "scheduling"],
    category: "AI Infra",
    hiring: "actively-hiring",
    openings: 6,
    status: "none",
    lastActivity: "3d",
    followup: false,
    note: ""
  },
  {
    id: "harbor-grid",
    name: "Harbor Grid",
    domain: "harborgrid.io",
    initials: "HG",
    color: "oklch(0.74 0.14 95)",
    desc: "Power-aware compute placement for sustainable AI workloads.",
    location: "Remote (US/EU)",
    size: "24",
    funding: "Series A",
    comp: "$200–$270k + 0.4–0.8%",
    tags: ["rust", "ai-infra", "energy"],
    category: "AI Infra",
    hiring: "actively-hiring",
    openings: 4,
    status: "saved",
    lastActivity: "1w",
    followup: false,
    note: ""
  },
  {
    id: "ironwood",
    name: "Ironwood",
    domain: "ironwood.dev",
    initials: "IW",
    color: "oklch(0.72 0.16 45)",
    desc: "Async-first web framework with zero-cost middleware composition.",
    location: "Remote (Global)",
    size: "6",
    funding: "Pre-seed",
    comp: "$150–$200k + 2.0–4.0%",
    tags: ["rust", "frameworks", "web"],
    category: "Developer Tools",
    hiring: "actively-hiring",
    openings: 2,
    status: "none",
    lastActivity: "1d",
    followup: false,
    note: ""
  },
  {
    id: "cinder",
    name: "Cinder",
    domain: "cinder.run",
    initials: "CI",
    color: "oklch(0.66 0.18 22)",
    desc: "Incident-response automation with replayable system snapshots.",
    location: "Remote (Americas)",
    size: "18",
    funding: "Seed",
    comp: "$190–$250k + 0.7–1.4%",
    tags: ["rust", "security", "automation"],
    category: "Security",
    hiring: "actively-hiring",
    openings: 3,
    status: "applied",
    lastActivity: "10d",
    followup: true,
    note: "Heard back from Yael — onsite slot opening up."
  },
  {
    id: "parallax",
    name: "Parallax",
    domain: "parallax.engineering",
    initials: "PA",
    color: "oklch(0.62 0.11 285)",
    desc: "Synthesized type-safe gRPC ↔ HTTP gateways from a single schema.",
    location: "Remote (Global)",
    size: "13",
    funding: "Seed",
    comp: "$180–$240k + 0.9–1.6%",
    tags: ["rust", "networking", "devtools"],
    category: "Developer Tools",
    hiring: "actively-hiring",
    openings: 2,
    status: "saved",
    lastActivity: "4d",
    followup: false,
    note: ""
  },
  {
    id: "boreal",
    name: "Boreal",
    domain: "boreal.systems",
    initials: "BO",
    color: "oklch(0.70 0.13 195)",
    desc: "Cold-storage tier with O(1) random access via novel encoding.",
    location: "Remote (EU)",
    size: "15",
    funding: "Seed",
    comp: "$180–$240k + 0.8–1.5%",
    tags: ["rust", "storage", "databases"],
    category: "Infrastructure",
    hiring: "no-openings",
    openings: 0,
    status: "none",
    lastActivity: "6w",
    followup: false,
    note: ""
  }
];

window.FILTER_GROUPS = [
  {
    id: "status",
    title: "Tracking",
    options: [
      { id: "applied", label: "Applied", color: "accent", count: 5 },
      { id: "interviewing", label: "Interviewing", color: "rust", count: 2 },
      { id: "saved", label: "Saved", color: "fg-2", count: 7 },
      { id: "rejected", label: "Rejected", color: "danger", count: 1 },
      { id: "followup", label: "Follow-up due", color: "warn", count: 5 }
    ]
  },
  {
    id: "hiring",
    title: "Hiring state",
    options: [
      { id: "actively-hiring", label: "Actively hiring", color: "ok" },
      { id: "selective", label: "Selective", color: "warn" },
      { id: "no-openings", label: "No openings", color: "fg-3" }
    ]
  },
  {
    id: "category",
    title: "Category",
    options: [
      { id: "Infrastructure", label: "Infrastructure" },
      { id: "AI Infra", label: "AI Infra" },
      { id: "Platform", label: "Platform" },
      { id: "Databases", label: "Databases" },
      { id: "Security", label: "Security" },
      { id: "Developer Tools", label: "Developer Tools" },
      { id: "Embedded", label: "Embedded" }
    ]
  },
  {
    id: "remote",
    title: "Remote region",
    options: [
      { id: "Global", label: "Global" },
      { id: "US", label: "Americas" },
      { id: "EU", label: "EU" }
    ]
  },
  {
    id: "stage",
    title: "Funding stage",
    options: [
      { id: "Pre-seed", label: "Pre-seed" },
      { id: "Seed", label: "Seed" },
      { id: "Series A", label: "Series A" },
      { id: "Series B", label: "Series B" },
      { id: "Series C", label: "Series C" }
    ]
  }
];

window.STATUS_META = {
  applied: { label: "Applied", color: "var(--accent)", bg: "var(--accent-soft)" },
  interviewing: { label: "Interviewing", color: "var(--rust)", bg: "var(--rust-soft)" },
  saved: { label: "Saved", color: "var(--fg-2)", bg: "oklch(0.5 0 0 / 0.1)" },
  rejected: { label: "Rejected", color: "var(--danger)", bg: "var(--danger-soft)" },
  none: { label: "Not tracked", color: "var(--fg-3)", bg: "transparent" }
};

window.HIRING_META = {
  "actively-hiring": { label: "Actively hiring", color: "var(--ok)" },
  "selective": { label: "Selective", color: "var(--warn)" },
  "no-openings": { label: "No openings", color: "var(--fg-3)" }
};
